# Generated by Django 6.0.6 on 2026-06-17 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_options'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('intermediate', 'Intermediate Assessment'), ('report', 'Report Evaluation'), ('presentation', 'Presentation/Review'), ('mentor', 'Mentor Evaluation'), ('viva', 'Final Viva'), ('other', 'Other')], max_length=20)),
                ('default_max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('assignment_level', models.CharField(choices=[('programme', 'Programme'), ('batch', 'Batch'), ('student', 'Student'), ('internship', 'Internship Specific')], default='student', max_length=20)),
                ('related_semester', models.CharField(blank=True, max_length=50)),
                ('reason_for_change', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mentors', to=settings.AUTH_USER_MODEL)),
                ('faculty_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='authentication.userprofile')),
                ('internship_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_assignments', to='core.internshiprecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='core.student')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentMarks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks_awarded', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='core.assessmentcomponent')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL)),
                ('internship_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='core.internshiprecord')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('internship_record', 'assessment_component')},
            },
        ),
        migrations.CreateModel(
            name='ConsolidatedScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regular_internship_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assessment_internship_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_consolidated_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calculation_formula', models.CharField(default='simple_average', max_length=100)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_scores', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_scores', to='core.student')),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('student', 'calculation_formula')},
            },
        ),
    ]
