# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assessmentconfiguration_auditlog_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_type_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
