# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organisation_type_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiprecord',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='internship_documents/'),
        ),
    ]
