# Generated by Codex on 2026-06-24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_internshiprecord_supporting_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.department'),
        ),
        migrations.AddField(
            model_name='internshiprecord',
            name='academic_phase',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='internshiprecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentmarks',
            name='assessment_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentmarks',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='assessment_documents/'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentmarks',
            unique_together=set(),
        ),
    ]
