# Generated by Django 6.0.6 on 2026-06-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_student_batch_alter_student_degree_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiprecord',
            name='certificate_upload',
            field=models.FileField(blank=True, null=True, upload_to='internship_certificates/'),
        ),
        migrations.AddField(
            model_name='internshiprecord',
            name='date_override_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internshiprecord',
            name='date_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internshiprecord',
            name='report_upload',
            field=models.FileField(blank=True, null=True, upload_to='internship_reports/'),
        ),
    ]
