# Generated by Django 6.0.6 on 2026-09-08 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_internshiprecord_certificate_upload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorassignment',
            name='allow_co_mentor',
            field=models.BooleanField(default=False, help_text='Allow another active mentor assignment to overlap with this one for the same student/scope.'),
        ),
        migrations.AddConstraint(
            model_name='internshiprecord',
            constraint=models.UniqueConstraint(condition=models.Q(('internship_type__in', ['regular', 'assessment'])), fields=('student', 'internship_type', 'internship_number'), name='unique_internship_number_per_type_per_student'),
        ),
    ]
