# Generated by Django 6.0.6 on 2026-06-09 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('academic', 'Academic Break'), ('internship', 'Internship Break'), ('medical', 'Medical Break'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='break_documents/')),
                ('impact_on_internship', models.TextField(blank=True, help_text='How this break affects internship schedule or marks', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organisation_type', models.CharField(choices=[('advocate', 'Advocate'), ('law_firm', 'Law Firm'), ('ngo', 'NGO'), ('court', 'Court'), ('company', 'Company'), ('government', 'Government Office'), ('other', 'Other')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('area_of_work', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('feedback_rating', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('duration_years', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='internship',
            name='company',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='department',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='internship',
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='student',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='enrollment_no',
            new_name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('dept_admin', 'Department Admin'), ('faculty_mentor', 'Faculty Mentor'), ('faculty_evaluator', 'Faculty Evaluator'), ('hod', 'HoD/Programme Coordinator'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('record_id', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InternshipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_type', models.CharField(choices=[('regular', 'Regular Internship'), ('assessment', 'Assessment Internship'), ('additional', 'Additional Internship'), ('repeated', 'Repeated Internship')], default='regular', max_length=20)),
                ('internship_number', models.IntegerField(blank=True, help_text='1 to 8 for regular, null for assessment', null=True)),
                ('related_semester', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', max_length=20)),
                ('nature_of_work', models.TextField(blank=True, null=True)),
                ('student_submission_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_upload', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('report_upload', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('completion_status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('not_completed', 'Not Completed'), ('repeated', 'Repeated')], default='pending', max_length=20)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_correction', 'Needs Correction')], default='draft', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_internships', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_records', to='apps.organisation')),
            ],
            options={
                'ordering': ['student', 'internship_number'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('intermediate', 'Intermediate Assessment'), ('report', 'Report Evaluation'), ('presentation', 'Presentation/Review'), ('mentor', 'Mentor Evaluation'), ('viva', 'Final Viva'), ('other', 'Other')], max_length=20)),
                ('assessment_name', models.CharField(max_length=100)),
                ('maximum_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('marks_awarded', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weightage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessed_marks', to=settings.AUTH_USER_MODEL)),
                ('internship_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='apps.internshiprecord')),
            ],
            options={
                'ordering': ['internship_record', 'assessment_date', 'assessment_type'],
                'unique_together': {('internship_record', 'assessment_type', 'assessment_name')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('needs_correction', 'Needs Correction'), ('marks_entered', 'Marks Entered'), ('marks_updated', 'Marks Updated')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('assessment_marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='apps.assessmentmarks')),
                ('internship_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='apps.internshiprecord')),
            ],
            options={
                'verbose_name_plural': 'Approval Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=20)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.CharField(max_length=20)),
                ('academic_year_start', models.IntegerField()),
                ('academic_year_end', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='apps.programme')),
            ],
            options={
                'unique_together': {('programme', 'batch_year')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_internship_count', models.IntegerField(default=8)),
                ('assessment_internship_enabled', models.BooleanField(default=True)),
                ('assessment_internship_duration_months', models.IntegerField(default=3)),
                ('include_intermediate_marks', models.BooleanField(default=False)),
                ('calculation_formula', models.CharField(choices=[('simple_average', 'Simple Average'), ('weighted_average', 'Weighted Average'), ('best_n', 'Best N Internships'), ('all_with_assessment', 'All Internships + Assessment'), ('separate_components', 'Separate Components')], default='simple_average', max_length=50)),
                ('best_n_value', models.IntegerField(blank=True, default=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_configs', to='apps.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('degree_start_date', models.DateField()),
                ('degree_end_date', models.DateField()),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('on_break', 'On Break')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.batch')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.programme')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('assignment_level', models.CharField(choices=[('student', 'Student Level'), ('batch', 'Batch Level'), ('internship', 'Internship Specific')], default='student', max_length=20)),
                ('related_semester', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_for_change', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mentors', to=settings.AUTH_USER_MODEL)),
                ('faculty_mentor', models.ForeignKey(limit_choices_to={'role__in': ['faculty_mentor', 'dept_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to=settings.AUTH_USER_MODEL)),
                ('internship_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_assignments', to='apps.internshiprecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='apps.student')),
            ],
            options={
                'ordering': ['student', '-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='internshiprecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_records', to='apps.student'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certificate', 'Internship Certificate'), ('report', 'Internship Report'), ('break_approval', 'Break Approval Document'), ('evaluation_sheet', 'Evaluation Sheet'), ('organisation_confirmation', 'Organisation Confirmation'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('break_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apps.breakrecord')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('internship_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apps.internshiprecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apps.student')),
            ],
        ),
        migrations.AddField(
            model_name='breakrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='apps.student'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
