# Generated by Django 6.0.6 on 2026-06-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('admin', 'System Admin'), ('dept_admin', 'Department Admin'), ('faculty_mentor', 'Faculty Mentor'), ('faculty_evaluator', 'Faculty Evaluator'), ('hod', 'HoD/Programme Coordinator'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
