# Generated by Django 6.0.6 on 2026-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofile_options_userprofile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('faculty_mentor', 'Faculty Mentor'), ('evaluator', 'Faculty Evaluator'), ('hod', 'HoD/Coordinator'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
